name: "Setup MySQL Cross-Platform"
description: "Installs and configures MySQL on macOS, Linux, and Windows"
author: "Kayque Govetri"

branding:
  icon: 'database'
  color: 'gray-dark'

inputs:
  mysql_root_password:
    description: 'Password for the MySQL root user'
    required: false
    default: 'root'
  mysql_port:
    description: 'Port to expose MySQL on the host'
    required: false
    default: '32768'
  mysql_database:
    description: 'Database to create on container start'
    required: false
  mysql_user:
    description: 'User to create on container start'
    required: false
  mysql_password:
    description: 'Password for the created user'
    required: false

runs:
  using: "composite"
  steps:
    - name: Make macOS script executable
      if: runner.os == 'macOS'
      shell: bash
      run: chmod +x "${GITHUB_ACTION_PATH}/entrypoint-macos.sh"

    - name: Run macOS script
      if: runner.os == 'macOS'
      shell: bash
      run: "${GITHUB_ACTION_PATH}/entrypoint-macos.sh"

    - name: Make Linux script executable
      if: runner.os == 'Linux'
      shell: bash
      run: chmod +x "${GITHUB_ACTION_PATH}/entrypoint-linux.sh"

    - name: Run Linux script
      if: runner.os == 'Linux'
      shell: bash
      run: "${GITHUB_ACTION_PATH}/entrypoint-linux.sh"

    - name: Run Windows script
      if: runner.os == 'Windows'
      shell: pwsh
      run: "& '${env:GITHUB_ACTION_PATH}\\entrypoint.ps1'"
