name: Test MySQL on Ubuntu

on:
  push:
    paths:
      - "entrypoint-linux.sh"
      - "action.yml"
  pull_request:
    paths:
      - "entrypoint-linux.sh"
      - "action.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          mysql_root_password: test123
          mysql_port: 3307
          mysql_database: my_test_db
          mysql_user: my_user
          mysql_password: my_user_pass
      - name: Verify Admin Socket Connection
        run: mysql -h 127.0.0.1 -P ${{github.env.mysql_port}} -u root -p ${{github.env.mysql_root_password}} -e "SELECT VERSION();"
      - name: Verify Admin TCP Connection
        run: mysql -h 127.0.0.1 -P ${{github.env.mysql_port}} -u root -p ${{github.env.mysql_root_password}} -e "SELECT VERSION();" --protocol=TCP
      - name: Verify User Socket Connection
        run: mysql -h 127.0.0.1 -P ${{github.env.mysql_port}} -u ${{github.env.my_user}} -p ${{github.env.mysql_password}} -e "SELECT VERSION();"
      - name: Verify User TCP Connection
        run: mysql -h 127.0.0.1 -P ${{github.env.mysql_port}} -u ${{github.env.my_user}} -p ${{github.env.mysql_password}} -e "SELECT VERSION();" --protocol=TCP
