name: Test MySQL on Ubuntu

on:
  push:
    paths:
      - 'entrypoint-linux.sh'
      - 'action.yml'
  pull_request:
    paths:
      - 'entrypoint-linux.sh'
      - 'action.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          mysql_root_password: test123
          mysql_port: 3307
          mysql_database: my_test_db
          mysql_user: my_user
          mysql_password: my_user_pass
