name: Test MySQL on macOS

on:
  push:
    paths:
      - 'entrypoint-macos.sh'
      - 'action.yml'
  pull_request:
    paths:
      - 'entrypoint-macos.sh'
      - 'action.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          mysql_root_password: test123
          mysql_port: 3307
          mysql_database: my_test_db
          mysql_user: my_user
          mysql_password: my_user_pass
