name: Test MySQL Setup Action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run local action
        uses: ./
        with:
          mysql_root_password: test123
          mysql_port: 3307
